# Generated by Django 5.2.6 on 2025-09-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.CharField(choices=[('fall', 'پاییز'), ('winter', 'زمستان'), ('spring', 'بهار'), ('summer', 'تابستان')], default='spring', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=1403),
        ),
    ]
