# Generated by Django 5.2.6 on 2025-09-20 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_remove_enrollment_use_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('template_pdf', models.FileField(blank=True, null=True, upload_to='assignment_templates/')),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_published', models.BooleanField(default=False)),
                ('regrade_enabled', models.BooleanField(default=False)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('x_position', models.FloatField(default=0)),
                ('y_position', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assignment')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RubricItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_items', to='assignments.assignment')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_pdf', models.FileField(blank=True, null=True, upload_to='student_submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submissions', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(choices=[('text', 'Text Comment'), ('pen', 'Freehand Drawing'), ('rectangle', 'Rectangle'), ('highlight', 'Highlight')], max_length=20)),
                ('page_number', models.PositiveIntegerField()),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('content', models.TextField(blank=True)),
                ('color', models.CharField(default='#2E5BBA', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_annotations', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='assignments.question')),
                ('rubric_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='assignments.rubricitem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='assignments.studentsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_grades', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_grades', to='assignments.question')),
                ('rubric_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assignments.rubricitem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_grades', to='assignments.studentsubmission')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('submission', 'question', 'rubric_item')},
            },
        ),
    ]
