# Generated by Django 5.2.6 on 2025-09-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='anonymized_grading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('homework', 'Homework'), ('exam', 'Exam'), ('project', 'Project'), ('quiz', 'Quiz')], default='homework', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='upload_by_student',
            field=models.BooleanField(default=True),
        ),
    ]
