# Generated by Django 5.2.6 on 2025-09-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0004_auto_20250920_1603"),
    ]

    operations = []
