# Generated by Django 5.2.6 on 2025-09-21 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_add_outline_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_points",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_grades",
                        to="assignments.question",
                    ),
                ),
                (
                    "selected_items",
                    models.ManyToManyField(
                        blank=True,
                        related_name="selected_in_grades",
                        to="assignments.rubricitem",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="assignments.submission",
                    ),
                ),
            ],
        ),
    ]
