# Generated by Django 5.2.6 on 2025-09-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0006_auto_20250921_1007"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rubricitem",
            name="description",
        ),
    ]
