# Generated by Django 5.2.6 on 2025-09-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('point_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('comment', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeRubricItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
