# Generated by Django 5.2.6 on 2025-09-06 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grade", "0001_initial"),
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="grader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grades_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="assignments.question",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="submissions.submission",
            ),
        ),
        migrations.AddField(
            model_name="graderubricitem",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selected_items",
                to="grade.grade",
            ),
        ),
        migrations.AddField(
            model_name="graderubricitem",
            name="rubric_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assignments.rubricitem"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("submission", "question")},
        ),
        migrations.AlterUniqueTogether(
            name="graderubricitem",
            unique_together={("grade", "rubric_item")},
        ),
    ]
