# Generated by Django 5.2.6 on 2025-09-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_instructor',
            field=models.BooleanField(default=False, help_text='Designates whether this user can create courses and act as an instructor.'),
        ),
    ]
